version: '2'
services:
  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      #- ./server-app/views:/usr/share/nginx/html
      - ./nginx/index.html:/srv/www/static/index.html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf