version: '2'
services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.2.3
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info # Set logging level to debug for more verbose logging
      - CORE_PEER_ID=cli
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/home/managedblockchain-tls-chain.pem
      - CORE_PEER_LOCALMSPID=m-GT45ZTXUSRDEVJUMV7ENWEVJBM
      - CORE_PEER_MSPCONFIGPATH=/opt/home/admin-msp
      - CORE_PEER_ADDRESS=nd-zwcdlx3xnbddtomr2nkzct2h3u.m-gt45ztxusrdevjumv7enwevjbm.n-qfi6ybakyfcxtaasjcp5lrwqdm.managedblockchain.us-east-1.amazonaws.com:30003
    working_dir: /opt/home
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/fabric-samples/chaincode:/opt/gopath/src/github.com/
      - /home/ubuntu/resource:/opt/home